### ISSUE TITLE
Updating Read Me with SQL Connection Properties for Java Server

### ISSUE THREAD

**Issue by stephenpaul2727** [airavata-courses/satyamsah#5]
Hi Satyam,

Everything is working great. One thing that I want to talk about is the spring boot server microservice that you wrote. In the application.properties. you have given credentials to localhost mysql server with your hardcoded values. So if the AI's or any other user who is using your application will get an sql exception as the configuration might not match to their localhost mysql environment. I would suggest you to update readme to download the folder instead of running jar. Then modify application.properties of the downloaded source code according to their localhost mysql config. Then they should be able to start java microservice without any problem.

**Comment by satyamsah** [comment]
Thanks Stephen for the kind response. I would like to highlight logic which you raised: 

Actually the java codes inside repo is not getting used for booting the application. It is just kept as reference as a part of open source so that other people can go through it. The jar "demo-0.0.1-SNAPSHOT.jar" is doing all the heavy lifting  and solely responsible for booting the service(but java should installed in the target system). So application profile does not have any importance as per running service is concerned . The magic is in the sql databases and tables you would have created by the 2 sql scripts. These sql scripts creates brand new sets of username, password , db and tables. Now these credentials should be matched with what is embedded in my logic inside that jar. If some body will to do some experiments and change values in my  mysql scripts (which I did not mention in my readme :) ) then there will be misssmatch as per the logic inside my jar. And only then the application will fail.

With respect to localhost issue. I am hoping they are running this microservice where the mysql is installed locally rather than in the other server. 

I hope you understand the logic. Else I can show you the demo.

**Comment by stephenpaul2727** [comment]
Yes,

My bad, I didn't see SQL scripts you wrote before. I understand the working logic behind it.
